[auth.anonymous]
# intentional misconfiguration MC-8: anonymous viewer access enabled
enabled = true
org_name = SpaceVE-1
org_role = Viewer

[security]
# intentional misconfiguration MC-8: default admin credentials
admin_user = admin
admin_password = admin

[server]
http_port = 3000
